# Generated by Django 2.0.7 on 2020-06-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('tenant_id', models.TextField()),
                ('display_name', models.TextField()),
                ('db_host', models.TextField()),
                ('db_instance', models.TextField()),
                ('status', models.TextField()),
                ('time', models.TextField()),
                ('errors', models.IntegerField()),
            ],
        ),
    ]
